version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=1234 # this is an example
      - POSTGRES_DB=postgres

volumes: 
 data: {}